name: Synchronize Blocklist AbuseIPDB (Country Specific Indonesia)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run abuseipdb_id.py
        run: python id-blocklist-abuseipdb/abuseipdb_id.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add id-blocklist-abuseipdb/abuseipdb-id-*.txt
          git commit -m "⚡️ SYNC ⚡️ $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
